is_train: True
ddp: False
gpus: [0]
stat: ts 
pre_frames: 4
root_path: ./
out_path: ./outputs/
project: semtalk_base
data_path: ""
e_path: ""
data_path_1: ""
hubert_mean_path: ""
hubert_std_path: ""
audio_infer_path: ""
base_ckpt: ""
vae_test_len: 32
vae_test_dim: 330
vae_test_stride: 20
vae_length: 240
vae_codebook_size: 256
vae_layer: 4
vae_grow: [1,1,2,1]
variational: False
# ckpt
load_ckpt: ""
test_ckpt: ""
# data config
training_speakers: [0, 1, 2, 3]
additional_data: False
cache_path: ""
dataset: show_base
train_path: ""
test_path: ""
new_cache: False

# motion config
ori_joints: beat_smplx_joints
tar_joints: beat_smplx_full
pose_rep: smplxflame_30
pose_norm: False
pose_fps: 30
rot6d: True
pre_frames: 4
pose_dims: 330
pose_length: 64
stride: 20
test_length: 64
motion_f: 256
m_pre_encoder: null
m_encoder: null
m_fix_pre: False

# audio config
audio_rep: onset+amplitude
audio_sr: 16000
audio_fps: 16000
audio_norm: False
audio_f: 256

# text config
word_rep: disabled_zero_placeholder
word_index_num: 0
word_dims: 0
freeze_wordembed: True
word_f: 0
t_pre_encoder: disabled
t_encoder: null
t_fix_pre: False

# facial config
facial_rep: smplxflame_30
facial_dims: 100
facial_norm: False
facial_f: 0
f_pre_encoder: null
f_encoder: null
f_fix_pre: False

# speaker config
id_rep: onehot
speaker_f: 0

# model config
batch_size: 64
# warmup_epochs: 1
# warmup_lr: 1e-6
lr_base: 1e-4
model: semtalk
g_name: semtalk_base
trainer: semtalk_base
hidden_size: 768
n_layer: 1
 
rec_weight: 1
grad_norm: 0.99
epochs: 200
test_period: 5
log_period: 10
decay_epochs: 999
# test_period: 0

ll: 3
lf: 3
lu: 3
lh: 3
cl: 1
cf: 1
cu: 1
ch: 1
